name: My blog

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Install just
      uses: extractions/setup-just@v3
    - name: Install dependencies
      run: |
        just sync
    - name: Generate static files
      run: |
        just generate
