name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install imagemagick
      run: |
        sudo apt install libpng-dev libjpeg-dev libtiff-dev imagemagick
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Install just
      uses: extractions/setup-just@v3
    - name: Install dependencies
      run: |
        just install
    - name: Generate for prod
      run: |
        ENV=prod just generate
